### ISSUE TITLE
Add SSR tutorial

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/react-tutorial#7]
The most important issue in React is SSR.
And if one does not learn the SSR in the React , there is no reason to use React.
Especially with Next vs. React.
**So practically if we do not learn SSR well in Meteor-React we have no reason to use Meteor-React**

**Comment by filipenevola** [comment]
Hi @Saeed-Bahrami, many projects use React without SSR and this is fine.

Next is a different framework, that rely a lot on SSR but React does not.

Are you willing to create a new tutorial using SSR for React? Your contribution would be very welcome.

**Comment by Saeed-Bahrami** [comment]
Hi @filipenevola , I was very surprised by your answer.
But about ssr, as far as I searched, Google has not yet fully assured that software made with Js has good Crawl and SEO. 
And if the Meteor combines with the React , it is no exception to this rule.
Many people use meteorites more with reaction. And I think you knew that too. And their main concern is to implement a complete SSR.
On the other hand, if the meteor can implement the SSR system flawlessly, many people who use react will be attracted to the meteor. Because definitely a meteor with a complete SSR system is better than next or any react based system. Because it has more possibilities.

When it comes to implementing SSR in meteor-react, I always tried to see myself in a very real project. And I also ran into problems that I have not been able to solve so far.
I think that if these issues and problems are collected, and examined, it will be possible to provide a complete and comprehensive education in this field. Of course, in this field, the main nuts of the Meteor need to be present.

> Are you willing to create a new tutorial using SSR for React? 

**And of course I welcome that**

**Comment by StorytellerCZ** [comment]
I agree with @filipenevola 
There are also other ways than SSR to achieve the same result. Galaxy uses [prerender.io](https://prerender.io/), there is also [otr.io pre-rendering](https://ostr.io/info/prerendering). To name a few non-SSR solutions.
In MCP we also have [React router SSR](https://github.com/Meteor-Community-Packages/react-router-ssr) project which takes care of that as well (which I will most likely implement in the future).

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.

**Comment by eugle** [comment]
@StorytellerCZ Still have no way to use the Galaxy in many countries and regions, such as in China, there is no way to put on record, so there is no way to use, you need to know this, China and the IT industry is very developed, the largest number of programmers, this is why the vue star is very high, if the Galaxy aimed with the server in China, and provide for the record, I believe that more people will choose to use the Galaxy, otherwise, you will lose the Chinese market
